21.04.2024 11:03:58.027 [HikariPool-1 housekeeper] WARN  c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=14h30m22s378ms988µs600ns).
21.04.2024 11:08:14.562 [main] WARN  o.h.orm.deprecation - HHH90000025: H2Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
21.04.2024 11:08:18.146 [main] WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
21.04.2024 11:08:21.010 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23505, SQLState: 23505
21.04.2024 11:08:21.017 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]
21.04.2024 11:08:21.031 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=vasia, password=7654, firstName=Vasiliy, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=belova@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]] [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; SQL [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; constraint ["PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]]
21.04.2024 11:08:21.485 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23505, SQLState: 23505
21.04.2024 11:08:21.486 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]
21.04.2024 11:08:21.487 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=anna_belova, password=7654, firstName=Vasiliy, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=vasvas@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]] [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; SQL [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; constraint ["PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]]
21.04.2024 11:08:22.008 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23502, SQLState: 23502
21.04.2024 11:08:22.008 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Значение NULL не разрешено для поля "FIRST_NAME"
NULL not allowed for column "FIRST_NAME"; SQL statement:
insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?) [23502-224]
21.04.2024 11:08:22.009 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=vasia, password=7654, firstName=null, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=vasvas@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [Значение NULL не разрешено для поля "FIRST_NAME"
NULL not allowed for column "FIRST_NAME"; SQL statement:
insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?) [23502-224]] [insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?)]; SQL [insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?)]; constraint [null]
21.04.2024 11:23:19.094 [HikariPool-1 housekeeper] WARN  c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=3m47s860ms515µs700ns).
21.04.2024 11:50:30.195 [HikariPool-1 housekeeper] WARN  c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m40s500ms53µs).
21.04.2024 12:02:10.169 [HikariPool-1 housekeeper] WARN  c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=6m9s921ms247µs).
21.04.2024 12:07:11.527 [main] WARN  o.h.orm.deprecation - HHH90000025: H2Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
21.04.2024 12:07:14.851 [main] WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
21.04.2024 12:07:17.262 [main] WARN  o.h.orm.deprecation - HHH90000025: H2Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
21.04.2024 12:07:17.994 [main] WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
21.04.2024 12:07:19.354 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23505, SQLState: 23505
21.04.2024 12:07:19.354 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]
21.04.2024 12:07:19.378 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=vasia, password=7654, firstName=Vasiliy, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=belova@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]] [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; SQL [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; constraint ["PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]]
21.04.2024 12:07:19.860 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23505, SQLState: 23505
21.04.2024 12:07:19.861 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]
21.04.2024 12:07:19.862 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=anna_belova, password=7654, firstName=Vasiliy, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=vasvas@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]] [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; SQL [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; constraint ["PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]]
21.04.2024 12:07:20.321 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23502, SQLState: 23502
21.04.2024 12:07:20.322 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Значение NULL не разрешено для поля "FIRST_NAME"
NULL not allowed for column "FIRST_NAME"; SQL statement:
insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?) [23502-224]
21.04.2024 12:07:20.323 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=vasia, password=7654, firstName=null, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=vasvas@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [Значение NULL не разрешено для поля "FIRST_NAME"
NULL not allowed for column "FIRST_NAME"; SQL statement:
insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?) [23502-224]] [insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?)]; SQL [insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?)]; constraint [null]
21.04.2024 12:07:21.263 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [1b4a432d-1ec9-4141-ace1-1d6ed2e3de00]. User does not exist
21.04.2024 12:07:21.347 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [099, 2024, GERMANY]. Invalid value for MonthOfYear (valid values 1 - 12): 99
21.04.2024 12:07:21.395 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [02, yyyy, GERMANY]. For input string: "yyyy"
21.04.2024 12:07:21.425 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [02, 2024, NON-EXIST COUNTY]. No enum constant com.example.online_toy_store.entity.enums.Country.NON-EXIST COUNTY
21.04.2024 12:07:21.566 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [PromoCode{pcId=null, promoName='Spring Surprise', discountAmount=15.5, startPromoDate=2024-08-20T00:00, endPromoDate=2024-08-31T00:00, amountOfUsers=50, unusedQuantity=50}]. The promo code already exist
21.04.2024 12:07:21.633 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [40.0]. The list of promo codes is empty
21.04.2024 12:07:21.669 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23503, SQLState: 23503
21.04.2024 12:07:21.670 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение ссылочной целостности: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"; SQL statement:
delete from promo_codes where pc_id=? [23503-224]
21.04.2024 12:07:21.672 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Spring Surprise]. could not execute statement [Нарушение ссылочной целостности: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"; SQL statement:
delete from promo_codes where pc_id=? [23503-224]] [delete from promo_codes where pc_id=?]; SQL [delete from promo_codes where pc_id=?]; constraint ["CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"; SQL statement:
delete from promo_codes where pc_id=? [23503-224]]
21.04.2024 12:07:21.701 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Non-existing promo code name]. Non-existing promo code name promo code not found
21.04.2024 12:07:21.745 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Non-existent name]. Non-existent name promo code not found
21.04.2024 12:07:21.826 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [4eab43a7-0385-48f3-bfd3-4529a2bcfd52]. Review does not exist
21.04.2024 12:07:22.218 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [6b4e8a7c-0f64-4fd8-a37f-5c0a072d14a3]. UNSUCCESSFULLY: order does not exist
21.04.2024 12:07:22.229 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [4eab43a7-0385-48f3-bfd3-4529a2bcfd52]. UNSUCCESSFULLY: order does not exist
21.04.2024 12:07:22.257 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Smile, orderDetailsDto=[OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift), OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=200, orderComment=I would like to get one pink car and one black car)])]. Less than 200 items left: 1:24 Toyota Yaris GR 2021 Alloy Car Diecasts Toy Vehicles Car Kid
21.04.2024 12:07:22.292 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23506, SQLState: 23506
21.04.2024 12:07:22.292 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение ссылочной целостности: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"; SQL statement:
insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?) [23506-224]
21.04.2024 12:07:22.295 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Smile, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb8, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. could not execute statement [Нарушение ссылочной целостности: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"; SQL statement:
insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?) [23506-224]] [insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?)]; SQL [insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?)]; constraint [CONSTRAINT_800A]
21.04.2024 12:07:22.330 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Black Friday, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. Invalid promotional code expiration date
21.04.2024 12:07:22.356 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23506, SQLState: 23506
21.04.2024 12:07:22.357 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение ссылочной целостности: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"; SQL statement:
insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?) [23506-224]
21.04.2024 12:07:22.358 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91d1, promoName=Smile, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. could not execute statement [Нарушение ссылочной целостности: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"; SQL statement:
insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?) [23506-224]] [insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?)]; SQL [insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?)]; constraint [CONSTRAINT_8B]
21.04.2024 12:07:22.394 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Invalid Name, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. There is no promotional code with this name
21.04.2024 12:07:22.416 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [invalidID]. showOrderById.id: !!! IT IS NOT [UUID] FORMAT
21.04.2024 12:07:22.493 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Non-existent name]. Supplier not found with name: Non-existent name
21.04.2024 12:07:22.555 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [4eab43a7-0385-48f3-bfd3-4529a2bcfd52]. Product does not exist
21.04.2024 12:07:22.587 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [invalidUUID]. Invalid UUID string: invalidUUID
21.04.2024 12:07:22.623 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [ProductBeforeCreatingDto(name=Small doll, description=Small beautifull doll, price=56.9, availableQuantity=10, category=INCORRECT CATEGORY, isAvailable=true, supplierName=Johnson, phone=+33 1 23 45 67 89, email=je@nterprises.com, address=14 Rue de la Republique, city=LYON, postal_code=12384, country=FRANCE)]. No enum constant com.example.online_toy_store.entity.enums.Category.INCORRECT CATEGORY
21.04.2024 12:07:22.653 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [ProductBeforeCreatingDto(name=Small doll, description=Small beautifull doll, price=56.9, availableQuantity=10, category=DOLLS, isAvailable=true, supplierName=Johnson E, phone=+33 1 23 45 67 89, email=je@nterprises.com, address=14 Rue de la Republique, city=INCORRECT CITY, postal_code=12384, country=FRANCE)]. No enum constant com.example.online_toy_store.entity.enums.City.INCORRECT CITY
21.04.2024 12:07:22.683 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [ProductBeforeCreatingDto(name=Small doll, description=Small beautifull doll, price=56.9, availableQuantity=10, category=DOLLS, isAvailable=true, supplierName=Johnson Enterprises Ltd, phone=+33 1 23 45 67 89, email=je@nterprises.com, address=14 Rue de la Republique, city=LYON, postal_code=12384, country=INCORRECT COUNTRY)]. No enum constant com.example.online_toy_store.entity.enums.Country.INCORRECT COUNTRY
21.04.2024 13:11:58.412 [main] WARN  o.h.orm.deprecation - HHH90000025: H2Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
21.04.2024 13:12:02.308 [main] WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
21.04.2024 13:12:05.102 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [6b4e8a7c-0f64-4fd8-a37f-5c0a072d14a3]. UNSUCCESSFULLY: order does not exist
21.04.2024 13:12:05.157 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [4eab43a7-0385-48f3-bfd3-4529a2bcfd52]. UNSUCCESSFULLY: order does not exist
21.04.2024 13:12:05.251 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Smile, orderDetailsDto=[OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift), OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=200, orderComment=I would like to get one pink car and one black car)])]. Less than 200 items left: 1:24 Toyota Yaris GR 2021 Alloy Car Diecasts Toy Vehicles Car Kid
21.04.2024 13:12:05.304 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23506, SQLState: 23506
21.04.2024 13:12:05.304 [main] ERROR o.h.e.j.s.SqlExceptionHelper - ????????? ????????? ???????????: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"; SQL statement:
insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?) [23506-224]
21.04.2024 13:12:05.318 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Smile, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb8, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. could not execute statement [????????? ????????? ???????????: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"; SQL statement:
insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?) [23506-224]] [insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?)]; SQL [insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?)]; constraint [CONSTRAINT_800A]
21.04.2024 13:12:05.360 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Black Friday, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. Invalid promotional code expiration date
21.04.2024 13:12:05.385 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23506, SQLState: 23506
21.04.2024 13:12:05.385 [main] ERROR o.h.e.j.s.SqlExceptionHelper - ????????? ????????? ???????????: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"; SQL statement:
insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?) [23506-224]
21.04.2024 13:12:05.386 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91d1, promoName=Smile, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. could not execute statement [????????? ????????? ???????????: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"; SQL statement:
insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?) [23506-224]] [insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?)]; SQL [insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?)]; constraint [CONSTRAINT_8B]
21.04.2024 13:12:05.427 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Invalid Name, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. There is no promotional code with this name
21.04.2024 13:12:05.452 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [invalidID]. showOrderById.id: !!! IT IS NOT [UUID] FORMAT
21.04.2024 13:12:05.594 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [4eab43a7-0385-48f3-bfd3-4529a2bcfd52]. Product does not exist
21.04.2024 13:12:05.635 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [invalidUUID]. Invalid UUID string: invalidUUID
21.04.2024 13:12:05.677 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [ProductBeforeCreatingDto(name=Small doll, description=Small beautifull doll, price=56.9, availableQuantity=10, category=INCORRECT CATEGORY, isAvailable=true, supplierName=Johnson, phone=+33 1 23 45 67 89, email=je@nterprises.com, address=14 Rue de la Republique, city=LYON, postal_code=12384, country=FRANCE)]. No enum constant com.example.online_toy_store.entity.enums.Category.INCORRECT CATEGORY
21.04.2024 13:12:05.716 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [ProductBeforeCreatingDto(name=Small doll, description=Small beautifull doll, price=56.9, availableQuantity=10, category=DOLLS, isAvailable=true, supplierName=Johnson E, phone=+33 1 23 45 67 89, email=je@nterprises.com, address=14 Rue de la Republique, city=INCORRECT CITY, postal_code=12384, country=FRANCE)]. No enum constant com.example.online_toy_store.entity.enums.City.INCORRECT CITY
21.04.2024 13:12:05.756 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [ProductBeforeCreatingDto(name=Small doll, description=Small beautifull doll, price=56.9, availableQuantity=10, category=DOLLS, isAvailable=true, supplierName=Johnson Enterprises Ltd, phone=+33 1 23 45 67 89, email=je@nterprises.com, address=14 Rue de la Republique, city=LYON, postal_code=12384, country=INCORRECT COUNTRY)]. No enum constant com.example.online_toy_store.entity.enums.Country.INCORRECT COUNTRY
21.04.2024 13:12:05.843 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [PromoCode{pcId=null, promoName='Spring Surprise', discountAmount=15.5, startPromoDate=2024-08-20T00:00, endPromoDate=2024-08-31T00:00, amountOfUsers=50, unusedQuantity=50}]. The promo code already exist
21.04.2024 13:12:05.880 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [40.0]. The list of promo codes is empty
21.04.2024 13:12:05.900 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23503, SQLState: 23503
21.04.2024 13:12:05.901 [main] ERROR o.h.e.j.s.SqlExceptionHelper - ????????? ????????? ???????????: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"; SQL statement:
delete from promo_codes where pc_id=? [23503-224]
21.04.2024 13:12:05.905 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Spring Surprise]. could not execute statement [????????? ????????? ???????????: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"; SQL statement:
delete from promo_codes where pc_id=? [23503-224]] [delete from promo_codes where pc_id=?]; SQL [delete from promo_codes where pc_id=?]; constraint ["CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"; SQL statement:
delete from promo_codes where pc_id=? [23503-224]]
21.04.2024 13:12:05.922 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Non-existing promo code name]. Non-existing promo code name promo code not found
21.04.2024 13:12:05.974 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Non-existent name]. Non-existent name promo code not found
21.04.2024 13:12:06.036 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [4eab43a7-0385-48f3-bfd3-4529a2bcfd52]. Review does not exist
21.04.2024 13:12:06.127 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Non-existent name]. Supplier not found with name: Non-existent name
21.04.2024 13:12:06.729 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23505, SQLState: 23505
21.04.2024 13:12:06.729 [main] ERROR o.h.e.j.s.SqlExceptionHelper - ????????? ??????????? ??????? ??? ?????????? ?????: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]
21.04.2024 13:12:06.737 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=vasia, password=7654, firstName=Vasiliy, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=belova@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [????????? ??????????? ??????? ??? ?????????? ?????: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]] [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; SQL [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; constraint ["PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]]
21.04.2024 13:12:07.219 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23505, SQLState: 23505
21.04.2024 13:12:07.219 [main] ERROR o.h.e.j.s.SqlExceptionHelper - ????????? ??????????? ??????? ??? ?????????? ?????: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]
21.04.2024 13:12:07.220 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=anna_belova, password=7654, firstName=Vasiliy, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=vasvas@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [????????? ??????????? ??????? ??? ?????????? ?????: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]] [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; SQL [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; constraint ["PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]]
21.04.2024 13:12:07.642 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23502, SQLState: 23502
21.04.2024 13:12:07.642 [main] ERROR o.h.e.j.s.SqlExceptionHelper - ???????? NULL ?? ????????? ??? ???? "FIRST_NAME"
NULL not allowed for column "FIRST_NAME"; SQL statement:
insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?) [23502-224]
21.04.2024 13:12:07.643 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=vasia, password=7654, firstName=null, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=vasvas@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [???????? NULL ?? ????????? ??? ???? "FIRST_NAME"
NULL not allowed for column "FIRST_NAME"; SQL statement:
insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?) [23502-224]] [insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?)]; SQL [insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?)]; constraint [null]
21.04.2024 13:12:08.351 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [1b4a432d-1ec9-4141-ace1-1d6ed2e3de00]. User does not exist
21.04.2024 13:12:08.374 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [099, 2024, GERMANY]. Invalid value for MonthOfYear (valid values 1 - 12): 99
21.04.2024 13:12:08.395 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [02, yyyy, GERMANY]. For input string: "yyyy"
21.04.2024 13:12:08.407 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [02, 2024, NON-EXIST COUNTY]. No enum constant com.example.online_toy_store.entity.enums.Country.NON-EXIST COUNTY
21.04.2024 13:12:08.731 [main] WARN  o.h.orm.deprecation - HHH90000025: H2Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
21.04.2024 13:12:09.377 [main] WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
21.04.2024 13:13:39.107 [main] WARN  o.h.orm.deprecation - HHH90000025: H2Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
21.04.2024 13:13:42.912 [main] WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
21.04.2024 13:13:45.157 [main] WARN  o.h.orm.deprecation - HHH90000025: H2Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
21.04.2024 13:13:45.954 [main] WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
21.04.2024 13:13:47.363 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23505, SQLState: 23505
21.04.2024 13:13:47.363 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]
21.04.2024 13:13:47.386 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=vasia, password=7654, firstName=Vasiliy, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=belova@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]] [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; SQL [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; constraint ["PUBLIC.CONSTRAINT_INDEX_B3 ON PUBLIC.USERS_INFO(EMAIL NULLS FIRST) VALUES ( /* 3 */ 'belova@gmail.com' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]]
21.04.2024 13:13:47.884 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23505, SQLState: 23505
21.04.2024 13:13:47.884 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]
21.04.2024 13:13:47.885 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=anna_belova, password=7654, firstName=Vasiliy, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=vasvas@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [Нарушение уникального индекса или первичного ключа: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]] [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; SQL [insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?)]; constraint ["PUBLIC.CONSTRAINT_INDEX_B ON PUBLIC.USERS_INFO(USER_NAME NULLS FIRST) VALUES ( /* 3 */ 'anna_belova' )"; SQL statement:
insert into users_info (address,card_number,city,email,password,postal_code,user_name,ui_id) values (?,?,?,?,?,?,?,?) [23505-224]]
21.04.2024 13:13:48.354 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23502, SQLState: 23502
21.04.2024 13:13:48.354 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Значение NULL не разрешено для поля "FIRST_NAME"
NULL not allowed for column "FIRST_NAME"; SQL statement:
insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?) [23502-224]
21.04.2024 13:13:48.354 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserBeforeCreatingDto(userName=vasia, password=7654, firstName=null, lastName=Vasiliev, country=FRANCE, address=Main Street, 35, city=LYON, postalCode=12344, email=vasvas@gmail.com, cardNumber=12345677788990009888)]. could not execute statement [Значение NULL не разрешено для поля "FIRST_NAME"
NULL not allowed for column "FIRST_NAME"; SQL statement:
insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?) [23502-224]] [insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?)]; SQL [insert into users (country,created_at,first_name,last_name,user_info,u_id) values (?,?,?,?,?,?)]; constraint [null]
21.04.2024 13:13:49.375 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [1b4a432d-1ec9-4141-ace1-1d6ed2e3de00]. User does not exist
21.04.2024 13:13:49.438 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [099, 2024, GERMANY]. Invalid value for MonthOfYear (valid values 1 - 12): 99
21.04.2024 13:13:49.476 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [02, yyyy, GERMANY]. For input string: "yyyy"
21.04.2024 13:13:49.507 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [02, 2024, NON-EXIST COUNTY]. No enum constant com.example.online_toy_store.entity.enums.Country.NON-EXIST COUNTY
21.04.2024 13:13:49.679 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [PromoCode{pcId=null, promoName='Spring Surprise', discountAmount=15.5, startPromoDate=2024-08-20T00:00, endPromoDate=2024-08-31T00:00, amountOfUsers=50, unusedQuantity=50}]. The promo code already exist
21.04.2024 13:13:49.735 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [40.0]. The list of promo codes is empty
21.04.2024 13:13:49.773 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23503, SQLState: 23503
21.04.2024 13:13:49.774 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение ссылочной целостности: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"; SQL statement:
delete from promo_codes where pc_id=? [23503-224]
21.04.2024 13:13:49.777 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Spring Surprise]. could not execute statement [Нарушение ссылочной целостности: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"; SQL statement:
delete from promo_codes where pc_id=? [23503-224]] [delete from promo_codes where pc_id=?]; SQL [delete from promo_codes where pc_id=?]; constraint ["CONSTRAINT_8B7: PUBLIC.ORDERS FOREIGN KEY(PROMO_CODE_ID) REFERENCES PUBLIC.PROMO_CODES(PC_ID) (CAST(X'62ae2a488c854f2eb7d891b374c94585' AS BINARY(16)))"; SQL statement:
delete from promo_codes where pc_id=? [23503-224]]
21.04.2024 13:13:49.803 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Non-existing promo code name]. Non-existing promo code name promo code not found
21.04.2024 13:13:49.847 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Non-existent name]. Non-existent name promo code not found
21.04.2024 13:13:49.932 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [4eab43a7-0385-48f3-bfd3-4529a2bcfd52]. Review does not exist
21.04.2024 13:13:50.297 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [6b4e8a7c-0f64-4fd8-a37f-5c0a072d14a3]. UNSUCCESSFULLY: order does not exist
21.04.2024 13:13:50.315 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [4eab43a7-0385-48f3-bfd3-4529a2bcfd52]. UNSUCCESSFULLY: order does not exist
21.04.2024 13:13:50.341 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Smile, orderDetailsDto=[OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift), OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=200, orderComment=I would like to get one pink car and one black car)])]. Less than 200 items left: 1:24 Toyota Yaris GR 2021 Alloy Car Diecasts Toy Vehicles Car Kid
21.04.2024 13:13:50.365 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23506, SQLState: 23506
21.04.2024 13:13:50.365 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение ссылочной целостности: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"; SQL statement:
insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?) [23506-224]
21.04.2024 13:13:50.368 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Smile, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb8, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. could not execute statement [Нарушение ссылочной целостности: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_800A: PUBLIC.ORDER_DETAILS FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS(P_ID) (CAST(X'3b287f306c1c4e71b7bf881e2d7b3cb8' AS BINARY(16)))"; SQL statement:
insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?) [23506-224]] [insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?)]; SQL [insert into order_details (order_id,order_comment,product_id,quantity,od_id) values (?,?,?,?,?)]; constraint [CONSTRAINT_800A]
21.04.2024 13:13:50.395 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Black Friday, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. Invalid promotional code expiration date
21.04.2024 13:13:50.416 [main] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: 23506, SQLState: 23506
21.04.2024 13:13:50.417 [main] ERROR o.h.e.j.s.SqlExceptionHelper - Нарушение ссылочной целостности: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"; SQL statement:
insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?) [23506-224]
21.04.2024 13:13:50.418 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91d1, promoName=Smile, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. could not execute statement [Нарушение ссылочной целостности: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"
Referential integrity constraint violation: "CONSTRAINT_8B: PUBLIC.ORDERS FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(U_ID) (CAST(X'184bc3b168064924924d6a66b6bf91d1' AS BINARY(16)))"; SQL statement:
insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?) [23506-224]] [insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?)]; SQL [insert into orders (order_date,order_status,promo_code_id,user_id,o_id) values (?,?,?,?,?)]; constraint [CONSTRAINT_8B]
21.04.2024 13:13:50.443 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [OrderDtoBefore(userId=184bc3b1-6806-4924-924d-6a66b6bf91df, promoName=Invalid Name, orderDetailsDto=[OrderDetailDto(productId=3b287f30-6c1c-4e71-b7bf-881e2d7b3cb4, quantity=1, orderComment=I would like to get one pink car and one black car), OrderDetailDto(productId=9ac0037b-2a2d-4c26-9b8c-15e720f0f8db, quantity=1, orderComment=Please package it nicely because it is a gift)])]. There is no promotional code with this name
21.04.2024 13:13:50.458 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [invalidID]. showOrderById.id: !!! IT IS NOT [UUID] FORMAT
21.04.2024 13:13:50.537 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [Non-existent name]. Supplier not found with name: Non-existent name
21.04.2024 13:13:50.615 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [4eab43a7-0385-48f3-bfd3-4529a2bcfd52]. Product does not exist
21.04.2024 13:13:50.648 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [invalidUUID]. Invalid UUID string: invalidUUID
21.04.2024 13:13:50.676 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [ProductBeforeCreatingDto(name=Small doll, description=Small beautifull doll, price=56.9, availableQuantity=10, category=INCORRECT CATEGORY, isAvailable=true, supplierName=Johnson, phone=+33 1 23 45 67 89, email=je@nterprises.com, address=14 Rue de la Republique, city=LYON, postal_code=12384, country=FRANCE)]. No enum constant com.example.online_toy_store.entity.enums.Category.INCORRECT CATEGORY
21.04.2024 13:13:50.695 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [ProductBeforeCreatingDto(name=Small doll, description=Small beautifull doll, price=56.9, availableQuantity=10, category=DOLLS, isAvailable=true, supplierName=Johnson E, phone=+33 1 23 45 67 89, email=je@nterprises.com, address=14 Rue de la Republique, city=INCORRECT CITY, postal_code=12384, country=FRANCE)]. No enum constant com.example.online_toy_store.entity.enums.City.INCORRECT CITY
21.04.2024 13:13:50.720 [main] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [ProductBeforeCreatingDto(name=Small doll, description=Small beautifull doll, price=56.9, availableQuantity=10, category=DOLLS, isAvailable=true, supplierName=Johnson Enterprises Ltd, phone=+33 1 23 45 67 89, email=je@nterprises.com, address=14 Rue de la Republique, city=LYON, postal_code=12384, country=INCORRECT COUNTRY)]. No enum constant com.example.online_toy_store.entity.enums.Country.INCORRECT COUNTRY
21.04.2024 16:04:35.586 [main] WARN  liquibase.changelog - liquibase.statement.core.CreateSequenceStatement is not supported on mysql, but createSequence will still execute
21.04.2024 16:04:35.592 [main] WARN  liquibase.changelog - liquibase.statement.core.CreateSequenceStatement is not supported on mysql, but createSequence will still execute
21.04.2024 16:04:35.642 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.suppliers'
21.04.2024 16:04:35.643 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.products'
21.04.2024 16:04:35.645 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.promo_codes'
21.04.2024 16:04:35.646 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.authorities'
21.04.2024 16:04:35.648 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.roles'
21.04.2024 16:04:35.649 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.authorities_roles'
21.04.2024 16:04:35.651 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.users_info'
21.04.2024 16:04:35.652 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.users_info_roles'
21.04.2024 16:04:35.654 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.users'
21.04.2024 16:04:35.656 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.orders'
21.04.2024 16:04:35.658 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.order_details'
21.04.2024 16:04:35.660 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.reviews'
21.04.2024 16:12:00.434 [http-nio-8080-exec-1] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserInfo{uID=null, userName='null', password='null', address='null', city=null, postalCode='null', email='null', cardNumber='null', roles=[Role{rId=null, roleName='manager'}, Role{rId=null, roleName='customer'}]}]. The given id must not be null
21.04.2024 16:17:06.079 [http-nio-8080-exec-1] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'PUT' is not supported]
21.04.2024 16:17:26.002 [http-nio-8080-exec-3] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserInfo{uID=null, userName='null', password='null', address='null', city=null, postalCode='null', email='null', cardNumber='null', roles=[Role{rId=null, roleName='manager'}, Role{rId=null, roleName='customer'}]}]. The given id must not be null
21.04.2024 16:19:28.293 [http-nio-8080-exec-2] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserInfo{uID=null, userName='null', password='null', address='null', city=null, postalCode='null', email='null', cardNumber='null', roles=[Role{rId=null, roleName='manager'}, Role{rId=null, roleName='customer'}]}]. The given id must not be null
21.04.2024 16:21:00.708 [http-nio-8080-exec-4] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserInfo{uID=null, userName='null', password='null', address='null', city=null, postalCode='null', email='null', cardNumber='null', roles=[Role{rId=null, roleName='manager'}, Role{rId=null, roleName='customer'}]}]. The given id must not be null
21.04.2024 16:21:14.954 [http-nio-8080-exec-2] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [UserInfo{uID=null, userName='null', password='null', address='null', city=null, postalCode='null', email='null', cardNumber='null', roles=[Role{rId=null, roleName='manager'}, Role{rId=null, roleName='customer'}]}]. The given id must not be null
21.04.2024 16:37:25.738 [http-nio-8080-exec-1] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [08ae72f7-4d3b-4fb1-bb0b-1aaae6b4a8ed, UserInfo{uID=null, userName='null', password='null', address='null', city=null, postalCode='null', email='null', cardNumber='null', roles=[Role{rId=null, roleName='manager'}, Role{rId=null, roleName='customer'}]}]. org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.example.online_toy_store.entity.Role
21.04.2024 16:37:25.742 [http-nio-8080-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.example.online_toy_store.entity.Role] with root cause
org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.example.online_toy_store.entity.Role
	at org.hibernate.metamodel.mapping.EntityIdentifierMapping.getIdentifierIfNotUnsaved(EntityIdentifierMapping.java:106)
	at org.hibernate.metamodel.mapping.internal.SimpleForeignKeyDescriptor.getAssociationKeyFromSide(SimpleForeignKeyDescriptor.java:489)
	at org.hibernate.metamodel.mapping.internal.ManyToManyCollectionPart.decompose(ManyToManyCollectionPart.java:199)
	at org.hibernate.persister.collection.BasicCollectionPersister.applyInsertRowValues(BasicCollectionPersister.java:450)
	at org.hibernate.persister.collection.mutation.InsertRowsCoordinatorStandard.insertRows(InsertRowsCoordinatorStandard.java:109)
	at org.hibernate.persister.collection.BasicCollectionPersister.recreate(BasicCollectionPersister.java:119)
	at org.hibernate.action.internal.CollectionRecreateAction.execute(CollectionRecreateAction.java:47)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:632)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:499)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:363)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:41)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1403)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:484)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2319)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1976)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:169)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:267)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:561)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:794)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:757)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:669)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:419)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at com.example.online_toy_store.service.impl.UserInfoServiceImpl$$SpringCGLIB$$0.updateUserInfo(<generated>)
	at com.example.online_toy_store.controller.UserInfoController.updateUserInfo(UserInfoController.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at com.example.online_toy_store.controller.UserInfoController$$SpringCGLIB$$0.updateUserInfo(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:259)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:192)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:920)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:830)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:888)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:840)
21.04.2024 16:41:56.934 [http-nio-8080-exec-1] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [08ae72f7-4d3b-4fb1-bb0b-1aaae6b4a8ed, UserInfo{uID=null, userName='null', password='null', address='null', city=null, postalCode='null', email='null', cardNumber='null', roles=[Role{rId=null, roleName='manager'}, Role{rId=null, roleName='customer'}]}]. org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.example.online_toy_store.entity.Role
21.04.2024 16:41:56.939 [http-nio-8080-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.example.online_toy_store.entity.Role] with root cause
org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.example.online_toy_store.entity.Role
	at org.hibernate.metamodel.mapping.EntityIdentifierMapping.getIdentifierIfNotUnsaved(EntityIdentifierMapping.java:106)
	at org.hibernate.metamodel.mapping.internal.SimpleForeignKeyDescriptor.getAssociationKeyFromSide(SimpleForeignKeyDescriptor.java:489)
	at org.hibernate.metamodel.mapping.internal.ManyToManyCollectionPart.decompose(ManyToManyCollectionPart.java:199)
	at org.hibernate.persister.collection.BasicCollectionPersister.applyInsertRowValues(BasicCollectionPersister.java:450)
	at org.hibernate.persister.collection.mutation.InsertRowsCoordinatorStandard.insertRows(InsertRowsCoordinatorStandard.java:109)
	at org.hibernate.persister.collection.BasicCollectionPersister.recreate(BasicCollectionPersister.java:119)
	at org.hibernate.action.internal.CollectionRecreateAction.execute(CollectionRecreateAction.java:47)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:632)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:499)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:363)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:41)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1403)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:484)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2319)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1976)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:169)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:267)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:561)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:794)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:757)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:669)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:419)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at com.example.online_toy_store.service.impl.UserInfoServiceImpl$$SpringCGLIB$$0.updateUserInfo(<generated>)
	at com.example.online_toy_store.controller.UserInfoController.updateUserInfo(UserInfoController.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at com.example.online_toy_store.controller.UserInfoController$$SpringCGLIB$$0.updateUserInfo(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:259)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:192)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:920)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:830)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:925)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:593)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:840)
21.04.2024 17:06:09.970 [HikariPool-1 housekeeper] WARN  c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=7m26s398ms256µs600ns).
21.04.2024 17:44:50.022 [http-nio-8080-exec-3] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [08ae72f7-4d3b-4fb1-bb0b-1aaae6b4a8ed, UserInfoUpdateRolesDto(isCustomer=true, isManager=true, isSuper_manager=null, isAdmin=false)]. Cannot invoke "java.util.Set.add(Object)" because the return value of "com.example.online_toy_store.entity.UserInfo.getRoles()" is null
21.04.2024 17:46:29.533 [http-nio-8080-exec-2] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [08ae72f7-4d3b-4fb1-bb0b-1aaae6b4a8ed, UserInfoUpdateRolesDto(isCustomer=true, isManager=true, isSuper_manager=null, isAdmin=false)]. Cannot invoke "java.util.Set.add(Object)" because the return value of "com.example.online_toy_store.entity.UserInfo.getRoles()" is null
21.04.2024 17:50:24.074 [http-nio-8080-exec-1] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [08ae72f7-4d3b-4fb1-bb0b-1aaae6b4a8ed, UserInfoUpdateRolesDto(isCustomer=true, isManager=true, isSuper_manager=true, isAdmin=false)]. Cannot invoke "java.util.Set.add(Object)" because the return value of "com.example.online_toy_store.entity.UserInfo.getRoles()" is null
21.04.2024 17:51:43.880 [http-nio-8080-exec-2] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [08ae72f7-4d3b-4fb1-bb0b-1aaae6b4a8ed, UserInfoUpdateRolesDto(isCustomer=true, isManager=true, isSuper_manager=true, isAdmin=false)]. Cannot invoke "java.util.Set.add(Object)" because the return value of "com.example.online_toy_store.entity.UserInfo.getRoles()" is null
21.04.2024 17:53:41.170 [http-nio-8080-exec-1] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [08ae72f7-4d3b-4fb1-bb0b-1aaae6b4a8ed, UserInfoUpdateRolesDto(isCustomer=true, isManager=true, isSuper_manager=true, isAdmin=false)]. Cannot invoke "java.util.Set.add(Object)" because the return value of "com.example.online_toy_store.entity.UserInfo.getRoles()" is null
21.04.2024 17:57:53.728 [http-nio-8080-exec-3] ERROR c.e.o.a.LoggingAspect - Request throw an exception. Cause - [08ae72f7-4d3b-4fb1-bb0b-1aaae6b4a8ed, UserInfoUpdateRolesDto(isCustomer=true, isManager=true, isSuper_manager=true, isAdmin=false)]. Cannot invoke "java.util.Set.add(Object)" because the return value of "com.example.online_toy_store.entity.UserInfo.getRoles()" is null
21.04.2024 18:10:29.225 [HikariPool-1 housekeeper] WARN  c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=12m21s686ms731µs800ns).
21.04.2024 18:13:55.981 [main] WARN  liquibase.changelog - liquibase.statement.core.CreateSequenceStatement is not supported on mysql, but createSequence will still execute
21.04.2024 18:13:55.988 [main] WARN  liquibase.changelog - liquibase.statement.core.CreateSequenceStatement is not supported on mysql, but createSequence will still execute
21.04.2024 18:13:56.036 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.suppliers'
21.04.2024 18:13:56.038 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.products'
21.04.2024 18:13:56.040 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.promo_codes'
21.04.2024 18:13:56.042 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.authorities'
21.04.2024 18:13:56.044 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.roles'
21.04.2024 18:13:56.046 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.authorities_roles'
21.04.2024 18:13:56.047 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.users_info'
21.04.2024 18:13:56.050 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.users_info_roles'
21.04.2024 18:13:56.051 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.users'
21.04.2024 18:13:56.053 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.orders'
21.04.2024 18:13:56.055 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.order_details'
21.04.2024 18:13:56.056 [main] WARN  liquibase.executor - Unknown table 'online_toy_store.reviews'
21.04.2024 18:20:27.769 [HikariPool-1 housekeeper] WARN  c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=3m32s142ms538µs800ns).
21.04.2024 18:32:32.190 [HikariPool-1 housekeeper] WARN  c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=6m33s893ms317µs100ns).
